#!/bin/bash

# Admin Panel API Test Commands
# Используйте эти команды для тестирования админ панели

BASE_URL="http://localhost:3000/api"
ADMIN_PASSWORD="admin2026"

echo "=========================================="
echo "Admin Panel API Test Commands"
echo "=========================================="
echo ""
echo "Base URL: $BASE_URL"
echo "Default Password: $ADMIN_PASSWORD"
echo ""

# 1. Health Check
echo "1️⃣  Health Check"
echo "$ curl -s $BASE_URL/health | jq ."
echo ""

# 2. Admin Login
echo "2️⃣  Admin Login"
echo "$ curl -X POST $BASE_URL/admin/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"password\":\"$ADMIN_PASSWORD\"}' | jq ."
echo ""
echo "# Then capture the token from response and use it below"
echo ""

# 3. Get Admin Stats (requires token)
echo "3️⃣  Get Admin Stats (Requires Authentication)"
echo "$ TOKEN='admin-token-$ADMIN_PASSWORD'"
echo "$ curl -s -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  $BASE_URL/admin/stats | jq ."
echo ""

# 4. Create Bot (requires token)
echo "4️⃣  Create Bot (Requires Authentication)"
echo "$ TOKEN='admin-token-$ADMIN_PASSWORD'"
echo "$ curl -X POST $BASE_URL/admin/bots \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  -d '{"
echo "    \"username\": \"@mybot\","
echo "    \"name\": \"My Bot\","
echo "    \"description\": \"A cool bot\","
echo "    \"categoryId\": 1,"
echo "    \"rating\": 4.5,"
echo "    \"reviewCount\": 10,"
echo "    \"isVerified\": true,"
echo "    \"isPremium\": false,"
echo "    \"tags\": [\"utility\", \"fun\"],"
echo "    \"monthlyUsers\": 1000,"
echo "    \"iconEmoji\": \"🤖\","
echo "    \"telegramUrl\": \"https://t.me/mybot\""
echo "  }' | jq ."
echo ""

# 5. Update Bot (requires token)
echo "5️⃣  Update Bot (Requires Authentication)"
echo "$ TOKEN='admin-token-$ADMIN_PASSWORD'"
echo "$ BOT_ID=1"
echo "$ curl -X PUT $BASE_URL/admin/bots/\$BOT_ID \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H \"Authorization: Bearer \$TOKEN\" \\"
echo "  -d '{"
echo "    \"username\": \"@mybot_updated\","
echo "    \"name\": \"My Updated Bot\","
echo "    \"description\": \"Updated description\","
echo "    \"categoryId\": 1,"
echo "    \"rating\": 4.8,"
echo "    \"reviewCount\": 15,"
echo "    \"isVerified\": true,"
echo "    \"isPremium\": true,"
echo "    \"tags\": [\"utility\", \"fun\", \"new\"],"
echo "    \"monthlyUsers\": 5000,"
echo "    \"iconEmoji\": \"🚀\","
echo "    \"telegramUrl\": \"https://t.me/mybot_updated\""
echo "  }' | jq ."
echo ""

# 6. Delete Bot (requires token)
echo "6️⃣  Delete Bot (Requires Authentication)"
echo "$ TOKEN='admin-token-$ADMIN_PASSWORD'"
echo "$ BOT_ID=1"
echo "$ curl -X DELETE $BASE_URL/admin/bots/\$BOT_ID \\"
echo "  -H \"Authorization: Bearer \$TOKEN\" | jq ."
echo ""

# 7. Error Cases
echo "7️⃣  Error Cases - No Authentication"
echo "$ curl -s $BASE_URL/admin/stats"
echo "# Response: Unauthorized (401)"
echo ""

echo "8️⃣  Error Cases - Invalid Token"
echo "$ curl -s -H 'Authorization: Bearer invalid-token' \\"
echo "  $BASE_URL/admin/stats"
echo "# Response: Invalid token (401)"
echo ""

echo "9️⃣  Error Cases - Wrong Password"
echo "$ curl -s -X POST $BASE_URL/admin/login \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"password\":\"wrongpassword\"}'"
echo "# Response: Invalid password (401)"
echo ""

echo "=========================================="
echo "Setup Instructions"
echo "=========================================="
echo ""
echo "1. Start the API Server:"
echo "   cd /workspaces/Tgbots2replit"
echo "   DATABASE_URL='postgresql://...' PORT=3000 pnpm start --filter @workspace/api-server"
echo ""
echo "2. Or with Node directly:"
echo "   PORT=3000 DATABASE_URL='...' node --enable-source-maps ./artifacts/api-server/dist/index.mjs"
echo ""
echo "3. Run automated tests:"
echo "   node test-admin-panel.js"
echo ""
echo "=========================================="
