import { db } from "@workspace/db";
import { botsTable, categoriesTable } from "@workspace/db/schema";
import { sql } from "drizzle-orm";

const categories = [
  { name: "AI & Нейросети", slug: "ai", emoji: "🤖" },
  { name: "Продуктивность", slug: "productivity", emoji: "⚡" },
  { name: "Развлечения", slug: "entertainment", emoji: "🎮" },
  { name: "Новости", slug: "news", emoji: "📰" },
  { name: "Финансы", slug: "finance", emoji: "💰" },
  { name: "Образование", slug: "education", emoji: "📚" },
  { name: "Музыка", slug: "music", emoji: "🎵" },
  { name: "Шопинг", slug: "shopping", emoji: "🛍️" },
  { name: "Путешествия", slug: "travel", emoji: "✈️" },
  { name: "Здоровье", slug: "health", emoji: "💪" },
];

const botsData = [
  {
    username: "ChatGPT_Bot",
    name: "ChatGPT",
    description: "Мощный AI-ассистент от OpenAI. Отвечает на вопросы, пишет тексты, помогает с кодом и анализирует данные.",
    categorySlug: "ai",
    rating: 4.9,
    reviewCount: 125400,
    isVerified: true,
    isPremium: false,
    tags: ["GPT-4", "Чат", "Код", "Текст"],
    monthlyUsers: 15000000,
    iconEmoji: "🧠",
  },
  {
    username: "MidJourney_Bot",
    name: "Midjourney AI Art",
    description: "Создавай потрясающие AI-изображения по текстовому описанию. Фотореализм, арт, иллюстрации.",
    categorySlug: "ai",
    rating: 4.8,
    reviewCount: 89200,
    isVerified: true,
    isPremium: true,
    tags: ["Изображения", "AI Art", "Творчество"],
    monthlyUsers: 8500000,
    iconEmoji: "🎨",
  },
  {
    username: "GrammarlyBot",
    name: "Grammarly",
    description: "Проверяет грамматику, орфографию и стиль текста. Поддерживает русский и английский языки.",
    categorySlug: "productivity",
    rating: 4.7,
    reviewCount: 45600,
    isVerified: true,
    isPremium: false,
    tags: ["Текст", "Грамматика", "Редактор"],
    monthlyUsers: 5200000,
    iconEmoji: "✏️",
  },
  {
    username: "NotionAI_Bot",
    name: "Notion AI",
    description: "AI-помощник для заметок и задач. Суммаризирует, переводит, создаёт планы и структурирует информацию.",
    categorySlug: "productivity",
    rating: 4.6,
    reviewCount: 32100,
    isVerified: true,
    isPremium: true,
    tags: ["Заметки", "AI", "Задачи"],
    monthlyUsers: 3800000,
    iconEmoji: "📝",
  },
  {
    username: "Meme_Generator_Bot",
    name: "Meme Factory",
    description: "Генерируй мемы за секунды! Тысячи шаблонов, редактор текста и готовые мемы для любого случая.",
    categorySlug: "entertainment",
    rating: 4.5,
    reviewCount: 67800,
    isVerified: false,
    isPremium: false,
    tags: ["Мемы", "Юмор", "Картинки"],
    monthlyUsers: 7200000,
    iconEmoji: "😂",
  },
  {
    username: "QuizBot",
    name: "Quiz Master",
    description: "Викторины на любую тему: история, наука, кино, спорт. Играй один или с друзьями в группе.",
    categorySlug: "entertainment",
    rating: 4.4,
    reviewCount: 28900,
    isVerified: false,
    isPremium: false,
    tags: ["Викторина", "Игра", "Знания"],
    monthlyUsers: 4100000,
    iconEmoji: "🧩",
  },
  {
    username: "BBCNewsBot",
    name: "BBC News",
    description: "Свежие новости от BBC. Мировые события, политика, технологии и спорт каждый час.",
    categorySlug: "news",
    rating: 4.7,
    reviewCount: 54300,
    isVerified: true,
    isPremium: false,
    tags: ["Мировые новости", "BBC", "Политика"],
    monthlyUsers: 9800000,
    iconEmoji: "📡",
  },
  {
    username: "TechCrunchBot",
    name: "TechCrunch Daily",
    description: "Новости технологий, стартапов и IT-индустрии от TechCrunch. Обновляется несколько раз в день.",
    categorySlug: "news",
    rating: 4.5,
    reviewCount: 31200,
    isVerified: true,
    isPremium: false,
    tags: ["Технологии", "Стартапы", "IT"],
    monthlyUsers: 5600000,
    iconEmoji: "💻",
  },
  {
    username: "CryptoSignalsBot",
    name: "Crypto Signals Pro",
    description: "Торговые сигналы для криптовалют. Анализ рынка, уведомления о ценах и прогнозы от AI.",
    categorySlug: "finance",
    rating: 4.3,
    reviewCount: 21600,
    isVerified: false,
    isPremium: true,
    tags: ["Крипто", "Торговля", "Сигналы"],
    monthlyUsers: 2900000,
    iconEmoji: "📈",
  },
  {
    username: "InvestHelperBot",
    name: "Invest Helper",
    description: "Анализ акций и ETF, новости фондового рынка, калькулятор доходности и портфельный трекер.",
    categorySlug: "finance",
    rating: 4.4,
    reviewCount: 18700,
    isVerified: true,
    isPremium: false,
    tags: ["Акции", "Инвестиции", "Аналитика"],
    monthlyUsers: 2200000,
    iconEmoji: "💹",
  },
  {
    username: "DuolingoBot",
    name: "Duolingo",
    description: "Учи иностранные языки в игровом формате. 40+ языков, ежедневные уроки и мотивационная система.",
    categorySlug: "education",
    rating: 4.8,
    reviewCount: 98400,
    isVerified: true,
    isPremium: false,
    tags: ["Языки", "Обучение", "Игра"],
    monthlyUsers: 12000000,
    iconEmoji: "🦉",
  },
  {
    username: "KhanAcademyBot",
    name: "Khan Academy",
    description: "Бесплатные видеоуроки по математике, физике, химии и другим предметам. От школьника до студента.",
    categorySlug: "education",
    rating: 4.6,
    reviewCount: 43200,
    isVerified: true,
    isPremium: false,
    tags: ["Математика", "Наука", "Видеоуроки"],
    monthlyUsers: 6700000,
    iconEmoji: "🎓",
  },
  {
    username: "SpotifyBot",
    name: "Spotify",
    description: "Управляй Spotify прямо из Telegram. Ищи треки, создавай плейлисты и делись музыкой с друзьями.",
    categorySlug: "music",
    rating: 4.5,
    reviewCount: 56700,
    isVerified: true,
    isPremium: false,
    tags: ["Музыка", "Плейлист", "Стриминг"],
    monthlyUsers: 8900000,
    iconEmoji: "🎧",
  },
  {
    username: "SoundHoundBot",
    name: "SoundHound",
    description: "Определяй музыку по мелодии или голосу. Отправь аудио и узнай название трека мгновенно.",
    categorySlug: "music",
    rating: 4.4,
    reviewCount: 23400,
    isVerified: false,
    isPremium: false,
    tags: ["Распознавание", "Музыка", "Поиск"],
    monthlyUsers: 3300000,
    iconEmoji: "🎵",
  },
  {
    username: "AliExpressBot",
    name: "AliExpress",
    description: "Поиск товаров на AliExpress, отслеживание заказов и уведомления о скидках и акциях.",
    categorySlug: "shopping",
    rating: 4.2,
    reviewCount: 78900,
    isVerified: true,
    isPremium: false,
    tags: ["Шопинг", "Скидки", "Доставка"],
    monthlyUsers: 11000000,
    iconEmoji: "🛒",
  },
  {
    username: "PriceTrackerBot",
    name: "Price Tracker",
    description: "Следи за ценами на товары в магазинах. Уведомления при снижении цены на Amazon, Ozon, Wildberries.",
    categorySlug: "shopping",
    rating: 4.5,
    reviewCount: 34100,
    isVerified: false,
    isPremium: false,
    tags: ["Цены", "Скидки", "Мониторинг"],
    monthlyUsers: 4500000,
    iconEmoji: "🏷️",
  },
  {
    username: "SkyscannerBot",
    name: "Skyscanner",
    description: "Поиск дешёвых авиабилетов и отелей. Сравнение цен, уведомления и бронирование прямо в Telegram.",
    categorySlug: "travel",
    rating: 4.6,
    reviewCount: 41800,
    isVerified: true,
    isPremium: false,
    tags: ["Авиабилеты", "Отели", "Путешествия"],
    monthlyUsers: 6200000,
    iconEmoji: "✈️",
  },
  {
    username: "WeatherBot",
    name: "Weather Pro",
    description: "Точный прогноз погоды на 7 дней для любого города мира. Часовые обновления и погодные предупреждения.",
    categorySlug: "travel",
    rating: 4.3,
    reviewCount: 62400,
    isVerified: false,
    isPremium: false,
    tags: ["Погода", "Прогноз", "Города"],
    monthlyUsers: 8700000,
    iconEmoji: "🌤️",
  },
  {
    username: "FitnessPlanBot",
    name: "AI Fitness Coach",
    description: "Персональный фитнес-план от AI. Тренировки, питание, трекинг прогресса и мотивационные напоминания.",
    categorySlug: "health",
    rating: 4.5,
    reviewCount: 29600,
    isVerified: false,
    isPremium: true,
    tags: ["Фитнес", "Тренировки", "AI"],
    monthlyUsers: 3900000,
    iconEmoji: "🏋️",
  },
  {
    username: "MeditationBot",
    name: "Calm & Meditate",
    description: "Медитации, дыхательные упражнения и техники снятия стресса. Для начинающих и опытных практиков.",
    categorySlug: "health",
    rating: 4.7,
    reviewCount: 38200,
    isVerified: true,
    isPremium: false,
    tags: ["Медитация", "Здоровье", "Стресс"],
    monthlyUsers: 5100000,
    iconEmoji: "🧘",
  },
  {
    username: "ClaudeAIBot",
    name: "Claude AI",
    description: "AI-ассистент от Anthropic с расширенным контекстом. Анализирует длинные документы и пишет подробные тексты.",
    categorySlug: "ai",
    rating: 4.8,
    reviewCount: 67300,
    isVerified: true,
    isPremium: false,
    tags: ["Claude", "Документы", "Анализ"],
    monthlyUsers: 9200000,
    iconEmoji: "✨",
  },
  {
    username: "PerplexityBot",
    name: "Perplexity AI",
    description: "AI-поисковик нового поколения. Ищет актуальную информацию в интернете и даёт ответы с источниками.",
    categorySlug: "ai",
    rating: 4.7,
    reviewCount: 48900,
    isVerified: true,
    isPremium: false,
    tags: ["Поиск", "AI", "Источники"],
    monthlyUsers: 7100000,
    iconEmoji: "🔍",
  },
  {
    username: "TranslatorBot",
    name: "DeepL Translator",
    description: "Лучший переводчик с AI. Поддерживает 30+ языков, сохраняет контекст и стиль речи при переводе.",
    categorySlug: "productivity",
    rating: 4.8,
    reviewCount: 112000,
    isVerified: true,
    isPremium: false,
    tags: ["Перевод", "Языки", "DeepL"],
    monthlyUsers: 18000000,
    iconEmoji: "🌐",
  },
  {
    username: "PDFBot",
    name: "PDF Manager",
    description: "Конвертируй, объединяй, сжимай и редактируй PDF прямо в Telegram. Быстро и без регистрации.",
    categorySlug: "productivity",
    rating: 4.6,
    reviewCount: 87300,
    isVerified: false,
    isPremium: false,
    tags: ["PDF", "Конвертация", "Документы"],
    monthlyUsers: 10500000,
    iconEmoji: "📄",
  },
];

async function seed() {
  console.log("Seeding database...");

  await db.execute(sql`TRUNCATE TABLE bots, categories RESTART IDENTITY CASCADE`);

  const insertedCategories = await db
    .insert(categoriesTable)
    .values(categories.map((c) => ({ name: c.name, slug: c.slug, emoji: c.emoji, count: 0 })))
    .returning();

  const categoryMap = new Map(insertedCategories.map((c) => [c.slug, c]));

  const botsToInsert = botsData.map((bot) => {
    const cat = categoryMap.get(bot.categorySlug)!;
    return {
      username: bot.username,
      name: bot.name,
      description: bot.description,
      category: cat.name,
      categoryId: cat.id,
      rating: bot.rating,
      reviewCount: bot.reviewCount,
      isVerified: bot.isVerified,
      isPremium: bot.isPremium,
      tags: bot.tags,
      monthlyUsers: bot.monthlyUsers,
      iconEmoji: bot.iconEmoji,
      telegramUrl: `https://t.me/${bot.username}`,
    };
  });

  await db.insert(botsTable).values(botsToInsert);

  for (const cat of insertedCategories) {
    const count = botsToInsert.filter((b) => b.categoryId === cat.id).length;
    await db.execute(
      sql`UPDATE categories SET count = ${count} WHERE id = ${cat.id}`
    );
  }

  console.log(`Seeded ${botsToInsert.length} bots in ${insertedCategories.length} categories`);
}

seed()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
